@startuml activity-3
title Управление учебной нагрузкой

|Заведующий кафедрой|
start
:Открыть раздел\n"Учебная нагрузка";
:Выбрать семестр;
:Просмотреть список дисциплин\nиз учебного поручения;

repeat
    :Выбрать дисциплину и вид занятия;
    :Выбрать преподавателя;
    
    if (Вид занятия допустим\nдля категории преподавателя?) then (нет)
        :Вывести предупреждение\nо нарушении ограничения;
        :Выбрать другого преподавателя;
    else (да)
        :Назначить преподавателя\nна вид занятия;
        :Обновить суммарную\nнагрузку преподавателя;
    endif
repeat while (Остались незакрытые\nвиды занятий?) is (да)

:Сохранить распределение нагрузки;

|Преподаватель|
:Открыть раздел\n"Моя нагрузка";
:Просмотреть назначенные\nдисциплины, группы\nи виды занятий;

stop
@enduml