@startuml activity-1
title Управление учебными планами

|Сотрудник деканата|
start
:Открыть раздел\n"Учебные планы";
:Выбрать действие;

if (Создать новый план?) then (да)
    :Указать год набора,\nфакультет, специальность;
    :Добавить дисциплины\nпо курсам и семестрам;
    :Указать часы по видам занятий\nи форму контроля;
    if (Все поля заполнены?) then (нет)
        :Вывести сообщение\nоб ошибке;
        stop
    else (да)
        :Сохранить учебный план;
    endif
else (нет)
    if (Редактировать план?) then (да)
        :Выбрать существующий план;
        if (Есть связанные поручения?) then (да)
            :Вывести предупреждение\nоб ограничениях;
        else (нет)
        endif
        :Внести изменения;
        :Сохранить изменения;
    else (нет)
        :Выбрать план для просмотра;
    endif
endif

|Студент|
:Открыть свой учебный план;
:Просмотреть перечень дисциплин\nпо семестрам;

stop
@enduml