@startuml activity-4a
title ВИ-11: Выставить оценки студентам
|Преподаватель|
|Система|

|Преподаватель|
start
:Открыть раздел "Ведомости";

|Система|
:Отобразить список дисциплин\nпреподавателя с формами контроля;

|Преподаватель|
:Выбрать дисциплину и группу;

|Система|
if (Дисциплина в учебном\nплане группы?) then (нет)
    :Вывести сообщение об ошибке;
    stop
else (да)
    :Загрузить список студентов группы;
    :Отобразить ведомость\nсо списком студентов;
endif

|Преподаватель|
:Выбрать студента;
:Ввести оценку;
:Нажать "Сохранить оценку";

|Система|
if (Оценка корректна?) then (нет)
    :Вывести сообщение об ошибке\nнекорректного значения;
else (да)
    :Сохранить оценку;
    :Зафиксировать дату,\nавтора изменения;
    :Обновить ведомость;
endif

|Преподаватель|
if (Выставить оценку\nследующему студенту?) then (да)
    :Выбрать следующего студента;
else (нет)
    stop
endif

stop
@enduml