@startuml activity-2b
title ВИ-09: Просмотреть учебное поручение
|Заведующий кафедрой|
|Система|

|Заведующий кафедрой|
start
:Открыть раздел\n"Учебные поручения";

|Система|
:Загрузить список поручений\nдля кафедры пользователя;
:Отобразить список поручений\nс указанием семестра и статуса;

|Заведующий кафедрой|
:Выбрать поручение\nдля просмотра;

|Система|
:Загрузить детали поручения;
:Отобразить перечень дисциплин,\nгрупп и видов занятий\nпо поручению;

|Заведующий кафедрой|
:Ознакомиться с поручением;

stop
@enduml